<a href="https://colab.research.google.com/github/Pritam-Mondal18/Machine-Learning-yt/blob/main/numpy_phase4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vecter operations


In [2]:
import numpy as np

In [5]:
vector1 = np.array([1,2,3,4,5,6])
vector2 =np.array([7,8,9,10,11,12])
# Adition of vectors
vec_Sum = vector1 + vector2
print("Sum of Vectors: ",vec_Sum)
# Multiplication of Vectors
vec_mul = vector1 * vector2
print("Multiplication of Vectors: ",vec_mul)
#Dot product
dot_product = np.dot(vector1,vector2)
print("Dot product of Vectors: ",dot_product)

Sum of Vectors:  [ 8 10 12 14 16 18]
Multiplication of Vectors:  [ 7 16 27 40 55 72]
Dot product of Vectors:  217


In [6]:
restaurant_types = np.array(['briyani','chinese','pizza','burger','cafe'])
vactorized_upper = np.vectorize(str.upper)
print("vectorized Upper",vactorized_upper(restaurant_types))

vectorized Upper ['BRIYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


# Brodcast


In [12]:
# Data Structure: [resturant_Id, 2021,2022,2023,2024]
sales_data = np.array([

[1,150000,180000,220000,250000],# paradise Briyani

[2,120000,140000,160000,190000], # Beijing Bites

[3,200000,230000,240000,270000], # Pizza Hub

[4,180000,210000,240000,270000], # Burger Point

[5,160000,185000,205000,230000] # Chai Point

])

In [14]:
monthly_avg = sales_data[:,1:]/12
print("Monthly Average:\n",monthly_avg)

Monthly Average:
 [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 20000.         22500.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
