<a href="https://colab.research.google.com/github/Pritam-Mondal18/Machine-Learning-yt/blob/main/numpy_phase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print("Original Array:", arr)

print("\nBasic Slicing: ",arr[2:7])
print("\nAdvanced/with Steps Slicing: ",arr[2:7:2])
print("\nNegative Slicing: ",arr[-3])

Original Array: [0 1 2 3 4 5 6 7 8 9]

Basic Slicing:  [2 3 4 5 6]

Advanced/with Steps Slicing:  [2 4 6]

Negative Slicing:  7


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr_2d)

print("\nSpecific Element Access: ",arr_2d[1,2])
print("\nRow Access: ",arr_2d[1,:])
print("\nColumn Access: ",arr_2d[:,1])

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific Element Access:  6

Row Access:  [4 5 6]

Column Access:  [2 5 8]


## Sorting

In [4]:
unsorted = np.array([2,0,1,6,5,4,3,8,9,7])
print("\nUnsorted Array:", np.sort(unsorted))

unSorted_2D = np.array([[3,1],[1,2],[3,2]])
print("\nUnsorted 2D Array:\n", unSorted_2D)
print("\n Sorted 2D array by column:\n", np.sort(unSorted_2D,axis=0))  # Sorts each column
print("\n Sorted 2D array by row:\n", np.sort(unSorted_2D,axis=1))  # Sorts each row


Unsorted Array: [0 1 2 3 4 5 6 7 8 9]

Unsorted 2D Array:
 [[3 1]
 [1 2]
 [3 2]]

 Sorted 2D array by column:
 [[1 1]
 [3 2]
 [3 2]]

 Sorted 2D array by row:
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("\nEven Numbers:", even_numbers)


Even Numbers: [ 2  4  6  8 10]


## Filter with mask

In [6]:
mask = numbers > 5
print("\nNumbers greater than 5:", numbers[mask])


Numbers greater than 5: [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [7]:
indices = [0,2,4]
print(numbers[indices])  # Fancy indexing

where_result = np.where(numbers>5)
print("\n",where_result)  # np.where() returns indices where condition is true
print("\nNP Where Result:", numbers[where_result])  # Accessing elements using np.where()

[1 3 5]

 (array([5, 6, 7, 8, 9]),)

NP Where Result: [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers>5, numbers*2, numbers)
print("\nCondition Array (numbers > 5):", condition_array)  # Conditional array creation


Condition Array (numbers > 5): [ 1  2  3  4  5 12 14 16 18 20]


In [9]:
condition_array = np.where(numbers>5, "true", "false")
print("\nCondition Array (numbers > 5):", condition_array)  # Conditional array creation

# for mor clarification
# if(numbers>5){
#     print("true")
# } else {
#     print("false")
# }


Condition Array (numbers > 5): ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']



### Adding and Removing data

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("\nArray 1:", arr1+arr2)  # Element-wise addition {1+4=5, 2+5=7, 3+6=9}
combined = np.concatenate((arr1,arr2))
print("\nCombined Array:", combined)  # Concatenation of arrays


Array 1: [5 7 9]

Combined Array: [1 2 3 4 5 6]


### Array Compatibilty

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Array Compatibility: ",a.shape == b.shape == c.shape)  # Check if arrays have the same shape

Array Compatibility:  True


In [12]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))  # Adding a new row (vertical stack[vstack])
# Note: new_row must have the same number of columns as original
print("\nOriginal Array:\n", original)
print("\nAfter adding new row:\n",with_new_row)

new_col = np.array([[5],[1]])
with_new_col = np.hstack((original,new_col))  # Adding a new column (horizontal stack[hstack])
# Note: new_col must have the same number of rows as original
print("\nAfter adding new col:\n",with_new_col)



Original Array:
 [[1 2]
 [3 4]]

After adding new row:
 [[1 2]
 [3 4]
 [5 6]]

After adding new col:
 [[1 2 5]
 [3 4 1]]



## Deletion

In [13]:
dlt = np.array([1,2,3,4,5,6])
deleted = np.delete(dlt,2)  # Deleting element at index 2
print("\nArray after deletion:", deleted)


Array after deletion: [1 2 4 5 6]
