<a href="https://colab.research.google.com/github/Pritam-Mondal18/Machine-Learning-yt/blob/main/numpy_phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy array and basics
learn about numpy

In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## List vs array

In [4]:
py_list = [1, 2, 3, 4, 5]
print("list multiplication:",py_list*2)

Py_array = np.array([1,2,3,4,5]) # element wise multiplication
print("array multiplication:",Py_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Numpy list time:", time.time() - start)

start = time.time()
Py_array = np.arange(1000000) * 2
print("Numpy array time:", time.time() - start)

list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
array multiplication: [ 2  4  6  8 10]
Numpy list time: 0.06954288482666016
Numpy array time: 0.007741689682006836


### Creating array from Scratch

In [5]:
py_Zeros = np.zeros((2,3))
print("\nZeros Array:\n", py_Zeros)

Py_Ones = np.ones((2,3))
print("\nOnes Array:\n", Py_Ones)

py_Empty = np.empty((2,3))
print("\nEmpty Array:\n", py_Empty)

py_full = np.full((2,3), 7)
print("\nFull Array:\n", py_full)

py_random = np.random.random((2,3))
print("\nRandom Array:\n", py_random)

py_secuence = np.arange(0,10,2)
print("\nSequence Array:", py_secuence)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Empty Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array:
 [[7 7 7]
 [7 7 7]]

Random Array:
 [[0.0854795  0.82161161 0.4631454 ]
 [0.47765231 0.22865699 0.97747102]]

Sequence Array: [0 2 4 6 8]


## Vector,Matrix,Tensor

In [6]:
vector = np.array([1,2,3])
print("Vector: ",vector)

Matrix = np.array([[1,2,3],[4,5,6]])
print("\nMatrix:\n", Matrix)

Tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print("\nTensor:\n", Tensor)

Vector:  [1 2 3]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


## Array properties


In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("\nDimensition: ",arr.ndim)
print("\n Size: ",arr.size)
print("\n Data Type: ",arr.dtype)

Shape:  (2, 3)

Dimensition:  2

 Size:  6

 Data Type:  int64


## Array Reshapping

In [8]:
arr_original =np.arange(12)
print("Original Array:\n", arr_original)

arr_reshaped = arr_original.reshape(3,4)
print("\nReshaped Array:\n", arr_reshaped)

arr_flattened = arr_reshaped.flatten()
print("\nFlattened Array:\n", arr_flattened)

# Raveling the array
# Raveling returns a flattened array, but it does not create a copy if possible
# it returns a view of the original array
# so changes in the raveled array will affect the original array if it is not a copy

arr_revaled = arr_reshaped.ravel()
print("\nRaveled Array:\n", arr_revaled)

# Transposing the array
# Transposing swaps the rows and columns
arr_Transposed = arr_reshaped.T
print("\nTransposed Array:\n", arr_Transposed)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
