<a href="https://colab.research.google.com/github/Pritam-Mondal18/Machine-Learning-yt/blob/main/numpy_phase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print("Original Array:", arr)

print("\nBasic Slicing: ",arr[2:7])
print("\nAdvanced/with Steps Slicing: ",arr[2:7:2])
print("\nNegative Slicing: ",arr[-3])

Original Array: [0 1 2 3 4 5 6 7 8 9]

Basic Slicing:  [2 3 4 5 6]

Advanced/with Steps Slicing:  [2 4 6]

Negative Slicing:  7


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr_2d)

print("\nSpecific Element Access: ",arr_2d[1,2])
print("\nRow Access: ",arr_2d[1,:])
print("\nColumn Access: ",arr_2d[:,1])

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific Element Access:  6

Row Access:  [4 5 6]

Column Access:  [2 5 8]


## Sorting

In [4]:
unsorted = np.array([2,0,1,6,5,4,3,8,9,7])
print("\nUnsorted Array:", np.sort(unsorted))

unSorted_2D = np.array([[3,1],[1,2],[3,2]])
print("\nUnsorted 2D Array:\n", unSorted_2D)
print("\n Sorted 2D array by column:\n", np.sort(unSorted_2D,axis=0))  # Sorts each column
print("\n Sorted 2D array by row:\n", np.sort(unSorted_2D,axis=1))  # Sorts each row


Unsorted Array: [0 1 2 3 4 5 6 7 8 9]

Unsorted 2D Array:
 [[3 1]
 [1 2]
 [3 2]]

 Sorted 2D array by column:
 [[1 1]
 [3 2]
 [3 2]]

 Sorted 2D array by row:
 [[1 3]
 [1 2]
 [2 3]]
